### ISSUE TITLE
Update to GPT3.5 or GPT4

### ISSUE THREAD

**Issue by duckduckgrayduck** [MuckRock/documentcloud-gpt3-playpen-addon#1]

**Comment by morisy** [comment]
Yeah, I think GPT 4 Turbo is worth doing. Not production scale yet but I think that we're at a level it's ok, and the cost + performance improvement make it a major upgrade. I think you can just set the model to `gpt-4-1106-preview` ? https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by duckduckgrayduck** [comment]
I've updated it to 3.5 Turbo for now. 

GPT-4 has a 32k context window ,but it's rate limit is 80,000 tokens per minute, which is like 3 documents per minute vs. 3.5 Turbo's 10 documents per minute. It is also a lot more expensive.

GPT-4 Turbo is promising at a 128k context window- but it's 5 million/day rate limit means the max is ~39 documents/day. 

I will re-visit this in a couple of months to see if GPT-4 Turbo gets a drop in the daily quota, or if regular GPT-4 bumps up the per minute window
